### PR TITLE
Allow popup from links

### PR DESCRIPTION
**Pull request by ailisp**
It is used in DevHub: https://near.social/#/devgovgigs.near/widget/gigs-board.pages.community.telegram?handle=protocol

currently the telegram message links has no effect, due to the sandbox setting

### CODE REVIEW

**Review by evgenykuzyakov — COMMENTED** [review]
I don't think uncontrolled popups is a good idea.

**Comment by ailisp** [comment]
Hi @evgenykuzyakov, allow-popups are executed with the sandbox flags, allow-popups-to-escape-sandbox will not:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox#syntax

so it should not introduce new security issue and equivalent to replace the iframe with the link url (if without `target="_blank"`), and equivalent to right click - open link in new tab (if with `target="_blank"`)

**Comment by evgenykuzyakov** [comment]
I think the issue is with `Window.open` that would open a new tab without a click? Can you make a demo to check if it's not the case.

**Comment by ailisp** [comment]
@evgenykuzyakov Oh you mentioned issue cannot be prevented. It can only make popup inherit sandbox-* options, but it doesn't prevent `Window.open`, so it can open new tab without click. I'll close this.

**Pull request closed without merging**
