### PR TITLE
Add Custom Gateway elements

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
- Introducing custom gateway elements. To define a custom element, a gateway can populate `customElements` argument in `initNear`. It's an optional object that can be used to register custom elements. The key is the name of the element, and the value is a function that returns a React component. For example:

```js
initNear({
  customElements: {
    Link: (props) => {
      if (!props.to && props.href) {
        props.to = props.href;
        delete props.href;
      }
      if (props.to) {
        props.to = sanitizeUrl(props.to);
      }
      return <Link {...props} />;
    },
  },
});
```

Example using custom element:

```jsx
return (
  <div>
    <Link to="mob.near/widget/Welcome">Hello World</Link>
  </div>
);
```

### CODE REVIEW

**Comment by calebjacob** [comment]
@evgenykuzyakov This is a great idea - I had been thinking of adding something like this for awhile now. There's only one problem though - we're currently migrating our viewer/gateway to Next JS, which has a unique `Link` component and router. Can we have the initializer accept a `Link` component instead of hardcoding it to use `react-router-dom`?

https://nextjs.org/docs/api-reference/next/link

**Comment by evgenykuzyakov** [comment]
> @evgenykuzyakov This is a great idea - I had been thinking of adding something like this for awhile now. There's only one problem though - we're currently migrating our viewer/gateway to Next JS, which has a unique `Link` component and router. Can we have the initializer accept a `Link` component instead of hardcoding it to use `react-router-dom`?
> 
> https://nextjs.org/docs/api-reference/next/link

Yep, we can inject it from the gateway.

**Review by calebjacob — APPROVED** [review]
Looks great!

**Comment by marcinbodnar** [comment]
FYI proper custom nextjs `Link` component:
```js
  customElements: {
    Link: ({ href, to, ...rest }: any) => <Link href={sanitizeUrl(href ?? to)} {...rest} />,
  },
```

**Pull request merged**
