### PR TITLE
iframe allow-same-origin to correctly calc size for iframe-resizer

### PR DESCRIPTION
**Pull request by ailisp**
Previously, the iframe-resizer doesn't work for iframe of dynamic content, console log shows that iframe-resizer cannot figure out the correct size of such iframe, resulting the iframe not correctly resized:

image

Adding allow-same-origin makes iframe-resizer works correctly:

image

### CODE REVIEW

**Comment by frol** [comment]
> allow-same-origin: The framed document is loaded into a unique origin, which means that all same-origin checks will fail; unique origins match no other origins ever, not even themselves. Among other impacts, this means that the document has no access to data stored in any origin's cookies or any other storage mechanisms (DOM storage, Indexed DB, etc.).

(c) https://web.dev/sandboxed-iframes/

Let’s think about the security model here. It seems that with this flag we open a door to [clickjacking attack](https://www.imperva.com/learn/application-security/clickjacking/), where BOS component can make a transparent iframe with an authenticated page (e.g. NEAR Wallet) and trick users to click so that user would transfer their assets (well, iframe-embedding should potentially be forbidden on wallet.near.org).

@ailisp I don’t see how this flag is related to the issue it solved, so I would dig deeper to understand what is actually going on there

**Comment by ailisp** [comment]
@frol I tried an iframe with sandbox options of all `allow-*` except `allow-same-origin` and iframe-resizer doesn't work again. Looking at inspector when the without `allow-same-origin` the resizer in iframe calculate the wrong size and send to the resizer in parent, and then the resizer in parent sets the wrong size.

Looking from the article you referred I found a clue:

> allow-same-origin is necessary, as twitter.com's cookies would otherwise be inaccessible, and the user couldn't log in to post the form.

image

So telegram's page is trying to set some cookie and that failed without allow-same-origin. Code after that line may be affected or not executed, which results in iframe-resizer doesn't figure out the right size. (Although i place iframe-resizer script before loading telegram's page)

Reference from MDN:
> allow-same-origin: If this token is not used, the resource is treated as being from a special origin that always fails the [same-origin policy](https://developer.mozilla.org/en-US/docs/Glossary/Same-origin_policy) (potentially preventing access to [data storage/cookies](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#cross-origin_data_storage_access) and some JavaScript APIs).

As a result if we cannot turn this option on, sites like t.me cannot properly work. I suggest we looking at options of rendering telegram messages ourselves.

**Comment by frol** [comment]
> As a result if we cannot turn this option on, sites like t.me cannot properly work. I suggest we looking at options of rendering telegram messages ourselves.

Yeah, I think it will be more productive afterall.

**Comment by ailisp** [comment]
Hi @evgenykuzyakov @calebjacob Can you confirm that this is a security problem and should not be allowed.

**Comment by calebjacob** [comment]
Hey @ailisp, I had the same problem and idea a little while ago, but it turns out the team didn't feel comfortable adding the `allow-same-origin` scope: https://github.com/NearSocial/VM/pull/34

@evgenykuzyakov will probably have a better explanation why we don't want to allow it.

**Comment by frol** [comment]
@ailisp #68 claims to solve the issue, could you check it?

**Comment by ailisp** [comment]
Thanks @calebjacob and @frol . Will try #68

**Comment by ailisp** [comment]
@frol #68 doesn't help for resizing telegram widgets. Looking at logs it's not the message not sending to parent iframe, but wrong size was sent. Every single telegram 150px, correct result should be variant based on content when allow-same-origin is set.

**Comment by ailisp** [comment]
@calebjacob since we cannot enable allow-same-origin, l'll close this issue and try rendering logics on our side to avoid iframe https://t.me widgets

**Pull request closed without merging**
